#!/bin/bash
set -e
rm -f /tmp/cif_httpd.pid
rm -f /tmp/cif_router.pid

# Pull in ENV vars for cif setup
/usr/local/bin/setup-cif-env.py

# Generate required tokens if they don't exist
/usr/local/bin/elasticsearch-token-setup.sh

# cp /var/lib/cif/.cif.yml /home/cif/
# cp /var/lib/cif/csirtg-smrt.yml /etc/cif/
# cp /var/lib/cif/cif-router.yml /etc/cif/

/usr/bin/supervisord -n -c /usr/local/etc/supervisord.conf
