---

version: '3'
services:
  cif:
    build: .
    container_name: cif-tiny
    restart: on-failure
    depends_on:
      - elasticsearch
    ports:
      - 5000:5000
    environment:
      CIFENV_CIF_STORE_STORE: "elasticsearch"
      CIFENV_CIF_STORE_NODES: "elasticsearch:9200"
    volumes:
      - cif-config:/etc/cif
      - cif-logs:/var/log/cif
      - cif-db:/var/lib/cif
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 30s
        timeout: 10s
        retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  cif-config:
  cif-logs:
  cif-db:
  esdata:
